# SPDX-FileCopyrightText: 2025 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

FROM python:3.11-alpine

RUN pip install --upgrade pip
RUN pip install requests requests_toolbelt metadict
