# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: test
permissions:
  contents: read

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test-plugins:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kong_version: ["2.8.3", "3.0", "3.4", "3.5", "3.8", "3.9.1", "3.9.3"]
        keycloak_version: ["26.0", "26.3"]
      fail-fast: false
    env:
      KONG_VERSION: ${{ matrix.kong_version }}
      KEYCLOAK_VERSION: ${{ matrix.keycloak_version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          submodules: "true"
      
      - name: Show Docker info
        run: |
          docker --version
          docker compose version
          
      - name: Run Tests
        run: docker compose build --no-cache && docker compose up --exit-code-from tests tests
      
      - name: Show container status
        if: failure()
        run: docker compose ps
      
      - name: Show Kong logs
        if: failure()
        run: docker compose logs kong
      
      - name: Show Keycloak logs
        if: failure()
        run: docker compose logs kc
      
      - name: Show test logs
        if: failure()
        run: docker compose logs tests
